# 服务器状态检查配置
servers:
  lobby:
    host: 127.0.0.1
    port: 25565
    timeout: 2000  # 连接超时时间（毫秒）
    interval: 5    # 检查间隔（秒）
  survival:
    host: 127.0.0.1
    port: 25566
    timeout: 2000
    interval: 5
  creative:
    host: 127.0.0.1
    port: 25567
    timeout: 2000
    interval: 5

# 占位符格式设置
placeholder:
  online-color: "&a"  # 在线状态颜色
  offline-color: "&c" # 离线状态颜色